# git-cliff configuration: https://git-cliff.org/docs/configuration

[changelog]
header = """
# Changelog

All notable changes to this project are documented in this file.

"""
body = """
{%- macro remote_url() -%}
  https://github.com/BeezKit-dev/web
{%- endmacro -%}

{% if version -%}
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}:** {% endif -%}
  {% if commit.breaking %}[**breaking**] {% endif -%}
  {{ commit.message | split(pat="\n") | first | upper_first | trim }} \
  ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))
{%- endfor %}
{% endfor %}
"""
footer = ""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
protect_breaking_commits = true
filter_commits = false
tag_pattern = "v[0-9]*"
sort_commits = "oldest"
commit_parsers = [
  { message = "^feat", group = "<!-- 00 -->Features" },
  { message = "^fix", group = "<!-- 01 -->Bug fixes" },
  { message = "^perf", group = "<!-- 02 -->Performance" },
  { message = "^refactor", group = "<!-- 03 -->Refactoring" },
  { message = "^docs", group = "<!-- 04 -->Documentation" },
  { message = "^test", group = "<!-- 05 -->Tests" },
  { message = "^ci", group = "<!-- 06 -->CI" },
  { message = "^build", group = "<!-- 07 -->Build" },
  { message = "^style", group = "<!-- 08 -->Styling" },
  { message = "^revert", group = "<!-- 09 -->Reverts" },
  { message = "^chore", group = "<!-- 10 -->Miscellaneous" },
]
